exclude_patterns:
- "test/"
- "**/*.test.js"
- "lib/"
- "build/"
- "dest/"
- "esm/"
- "scripts/"
- "docs/"
- "binaries/"
- "benchmark/"
- ".vscode/"
- ".github/"
- ".gitlab/"
- ".npmrc"
- ".nvmrc"
- ".gitignore"
- ".gitattributes"
- ".editorconfig"
- ".codeclimate.yml"
- "changelog-template.hbs"
- "CHANGELOG.md"
- "CODE_OF_CONDUCT.md"
- "CONTRIBUTING.md"
- "example.gif"
- "LICENSE.md"
- "package.json"
- "package-lock.json"
- "README.md"
- "yarn.lock"
- ".mailmap"
- ".snyk"
